---
# tasks file for install-k4k8s
- name: Apply the Kong Kubernetes manifest against the Kubernetes Cluster
  k8s:
    state: present
    src: "{{ files_dir_local }}/kong.yml"

- name: Configure Ingress Rules
  k8s:
    state: present
    src: "{{ ingress_dir }}/{{ item }}"
  with_items: 
    - orderbook.yml
