apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wallet-service
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /api/v1
        backend:
          serviceName: cea-wallet-service
          servicePort: 80
      - path: /swagger.json
        backend:
          serviceName: cea-wallet-service
          servicePort: 80
